In [83]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [122]:
df_train = pd.read_csv("C:\\Users\\pc\\Downloads\\blackfriday\\train.csv",encoding='latin-1')

In [ ]:
df_train.head()

In [ ]:
df_test = pd.read_csv("C:\\Users\\pc\\Downloads\\blackfriday\\test.csv",encoding='latin-1')

In [123]:
df_test.head()

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000004  P00128942      M  46-50           7             B   
1  1000009  P00113442      M  26-35          17             C   
2  1000010  P00288442      F  36-45           1             B   
3  1000010  P00145342      F  36-45           1             B   
4  1000011  P00053842      F  26-35           1             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               1                   1   
1                          0               0                   3   
2                         4+               1                   5   
3                         4+               1                   4   
4                          1               0                   4   

   Product_Category_2  Product_Category_3  
0                11.0                 NaN  
1                 5.0                 NaN  
2                14.0                 NaN  
3                 9.0                 NaN  
4                 5.0                12.0

In [124]:
df_merge=pd.merge(df_train,df_test,how='left')

In [ ]:
df_merge.head()

In [ ]:
df_merge[df_merge['Marital_Status'] != 0]

In [ ]:
df.info()

In [125]:
df.describe()

Age     Occupation  Marital_Status  Product_Category_1  \
count  550068.000000  550068.000000   550068.000000       550068.000000   
mean        2.496430       8.076707        0.409653            5.404270   
std         1.353632       6.522660        0.491770            3.936211   
min         0.000000       0.000000        0.000000            1.000000   
25%         2.000000       2.000000        0.000000            1.000000   
50%         2.000000       7.000000        0.000000            5.000000   
75%         3.000000      14.000000        1.000000            8.000000   
max         6.000000      20.000000        1.000000           20.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       550068.000000       166821.000000  550068.000000  
mean             9.260768           12.668243    9263.968713  
std              4.294093            4.125338    5023.065394  
min              2.000000            3.000000      12.000000  
25%              8.000000            9.000000    5823.000000  
50%              8.000000           14.000000    8047.000000  
75%             14.000000           16.000000   12054.000000  
max             18.000000           18.000000   23961.000000

In [ ]:
df_merge.drop(['User_ID'],axis=1,inplace=True)

In [126]:
df_merge.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [127]:
df_merge['Gender'] = df_merge['Gender'].map({'F': 0, 'M': 1})

In [128]:
df_merge.head()

User_ID Product_ID  Gender   Age  Occupation City_Category  \
0  1000001  P00069042       0  0-17          10             A   
1  1000001  P00248942       0  0-17          10             A   
2  1000001  P00087842       0  0-17          10             A   
3  1000001  P00085442       0  0-17          10             A   
4  1000002  P00285442       1   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [28]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [30]:
df['Age'] = label_encoder.fit_transform(df['Age'])
df['Age'].unique()

array([0, 6, 2, 4, 5, 3, 1])

In [32]:
df_merge['Age'] = label_encoder.fit_transform(df['Age'])
df_merge['Age'].unique()

array([0, 6, 2, 4, 5, 3, 1], dtype=int64)

In [129]:
df['Age'].unique()

array([0, 6, 2, 4, 5, 3, 1])

In [130]:
df_merge['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [131]:
df_merge['Age'] = df_merge['Age'].map({
    '0-17': 1,
    '18-25': 2,
    '26-35': 3,
    '36-45': 4,
    '46-50': 5,
    '51-55': 6,
    '55+': 7
})


In [132]:
df_merge.head()

User_ID Product_ID  Gender  Age  Occupation City_Category  \
0  1000001  P00069042       0    1          10             A   
1  1000001  P00248942       0    1          10             A   
2  1000001  P00087842       0    1          10             A   
3  1000001  P00085442       0    1          10             A   
4  1000002  P00285442       1    7          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

# why to convert catarogical values to numerical values 


### 1.Machine Learning Algorithms:
Most machine learning models, such as linear regression, decision trees, and neural networks, require numerical inputs. Models cannot process categorical data (e.g., 'Male', 'Female', '0-17', '18-25') directly. By converting these categories into numbers, the algorithms can understand the data and process it effectively.

Gender example: Converting 'F' and 'M' to 0 and 1 allows a model to treat gender as a feature it can process numerically.

Age example: Similarly, converting age groups like '0-17', '18-25', etc., into numbers like 1, 2, 3, etc., allows models to process them as numerical values.

###  2.Avoids Misinterpretation:
When you leave categorical variables as strings, the model might interpret them as textual features. This could lead to incorrect assumptions. For example:

A machine learning model might interpret ('0-17' > '18-25') based on lexicographic order, which isn't the right interpretation. Converting these categories to numbers ensures they are treated numerically, preserving the intended logic.

### 3. Simplification:
When working with numerical data:

Mathematical operations (like addition, multiplication) can be performed more easily.

You can calculate distances (in clustering algorithms) or use other metrics that require numerical data.

### 4. Facilitates Comparison:
By converting categories to numbers, you can compare and analyze them more easily. For instance:

Age ranges: It's easier to see if a group with a higher number correlates with a specific outcome.

Gender: A model can learn patterns in the data related to gender, even if it's represented as 0 or 1.

### 5. Required by Some Algorithms:
Some algorithms specifically require numerical encoding of categorical features:

Logistic Regression: Expects numerical features.

Neural Networks: Work better with numerical inputs, as the underlying activation functions (like sigmoid, ReLU) are based on numbers

In [133]:
df_merge.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [134]:
df_merge.head()

User_ID Product_ID  Gender  Age  Occupation City_Category  \
0  1000001  P00069042       0    1          10             A   
1  1000001  P00248942       0    1          10             A   
2  1000001  P00087842       0    1          10             A   
3  1000001  P00085442       0    1          10             A   
4  1000002  P00285442       1    7          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [135]:
df_merge['Product_Category_2'].mode()[0]

8.0

In [136]:
df_merge['Product_Category_2']=df['Product_Category_2'].fillna(df['Product_Category_2'].mode()[0])

In [137]:
df_merge['Product_Category_2'].isnull().sum()

0

In [138]:
df_merge['Product_Category_3']=df['Product_Category_3'].fillna(df['Product_Category_3'].mode()[0])

In [139]:
df['Product_Category_3'].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [145]:
    df['Stay_In_Current_City_Years'].unique()

array(['2', '4', '3', '1', '0'], dtype=object)

In [144]:
df['Stay_In_Current_City_Years'] = df['Stay_In_Current_City_Years'].str.replace('\+', '', regex=True)

In [146]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  int64  
 3   Age                         550068 non-null  int64  
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          550068 non-null  float64
 10  Product_Category_3          550068 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(7), object(3)
memory usage: 50.4+ MB


Why convert object to int or float?
Numerical operations: You can't do math (like sum, mean, etc.) on strings.

Machine learning models: Models only accept numeric input, not text.

Memory efficiency: Integer/float types use less memory than object types.



In [150]:
df_merge['Stay_In_Current_City_Years'] = df['Stay_In_Current_City_Years'].astype(int)

In [149]:
df_merge['Stay_In_Current_City_Years'].isnull().sum()

0

In [151]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  int64  
 3   Age                         550068 non-null  int64  
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  int32  
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          550068 non-null  float64
 10  Product_Category_3          550068 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int32(1), int64(7), object(2)
memory usage: 48.3+ MB
